language: generic
sudo: required
services:
  - docker

env:
  global:
    - IMG_NAME="docker.io/mattsch/fedora-rpmfusion"
    - VER="27"
script:
  - 'docker login -u "$D_U" -p "$D_P"'
  - 'docker build --build-arg FEDVER=${VER} -t ${IMG_NAME}:${VER} -t ${IMG_NAME}:latest .'
  - 'docker push ${IMG_NAME}:${VER}'
  - 'docker push ${IMG_NAME}:latest'

if: branch = master
